name: Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 79d795a767da85bbba821b871265fd87d853d808
          submodules: recursive

      - name: 配置 vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{github.workspace}}/vcpkg'
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
          vcpkgTriplet: x64-windows-static
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: 编译
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'win-x64-static-release'
          buildPreset: 'win-x64-static-release'

      - name: 打包二进制
        uses: actions/upload-artifact@v4
        with:
          name: Windows_${{ github.ref_name }}_${{ github.sha }}
          path: |
            build/win-x64-static-release/Release/*.exe
            build/win-x64-static-release/Release/*.dll
          if-no-files-found: error
          retention-days: 90
